---

- hosts: 127.0.0.1
  connection: local
  user: root
  become: no
  gather_facts: false
  serial: 1

  vars_prompt:
  - name: "vcenter_name"
    prompt: "vCenter_hostname"
    private: no
  - name: "user"
    prompt: "vCenter username"
    private: no
  - name: "pw"
    prompt: "User's password"
    private: yes
  - name: "vm"
    prompt: "Enter new VM name"
    private: no

  tasks:
   - vmware_guest:
       hostname: "{{vCenter_hostname}}"
       username: "{{user}}"
       password: "{{pw}}"
       validate_certs: False
       name: "{{vm}}"
       template: 'Ubuntu 16.04 LTS'
       datacenter: Capitol View
       cluster: Capitol View
       folder: /Dev
       state: poweredoff
